### ISSUE TITLE
Adding external links to neurons

### ISSUE THREAD

**Issue by dteinferno** [JaneliaSciComp/Neuroptikon#40]
We have a group LabGuru account (an online lab notebook/wiki) where we keep experimental details about individual fly lines. It would be nice to be able to click on the inspector window for a given neuron and to then be able to follow a link directly to the webpage containing the relevant information. We would likely want the ability to have multiple links for any given neuron.

**Comment by csweaver** [comment]
Would it be useful for use to put a label for the link so that you don't see the full url? 

It would make writing the script to add links to a neuron marginally more difficult.

**Comment by dteinferno** [comment]
A label would be nice, but not necessary as the urls are fairly clean (e.g. https://my.labguru.com/biocollections/flies/181)

**Comment by csweaver** [comment]
I'll hold off on labels for now, I don't want to make the scripting too complex. Let me know if you need it and I can add it in.

**Comment by csweaver** [comment]
Feature included in latest commit.

See Scripts/Neuron Links.py for an example
