### ISSUE TITLE
Neuron Line Label

### ISSUE THREAD

**Issue by dteinferno** [JaneliaSciComp/Neuroptikon#57]
Specific neurons come from specific genetic fly lines. Thanks to your hard work, we now have the ability to add an image of one of these lines to an individual neuron.  Adding images of additional genetic lines and, more importantly, being able to add text line labels (e.g. '60D05' or '49H05') would be invaluable.

**Comment by csweaver** [comment]
Would it work to have a label for each image that you could use for the line name or for other info? 

Can I put the requirement to display more than one image in another ticket?

**Comment by dteinferno** [comment]
An image label would be great, and yes to putting the ability to display more than one image in another ticket. Thanks!

**Comment by csweaver** [comment]
Added feature in latest commit
