### ISSUE TITLE
Improve interactive speed

### ISSUE THREAD

**Issue by csweaver** [JaneliaSciComp/Neuroptikon#63]
With a large script performing actions takes too long and is frustrating to the user

**Comment by csweaver** [comment]
The problem reported in this particular case is related to the problem on windows where paths are  rendered as cylinders instead of lines because of problems with OSG polytope interceptor.

**Comment by cmbruns-hhmi** [comment]
Is there any headroom to reduce the complexity of the cylinder models? I wonder if that might help improve the performance.

**Comment by csweaver** [comment]
That's a good idea, I'll try reducing the step size for cylinders when used for arborizatons.

**Comment by csweaver** [comment]
Reducing step size for cylinders confers no noticeable speed-up. Time to investigate new options.

**Comment by csweaver** [comment]
Despite my predictions, switching back to lines instead of cylinders doesn't seem to increase speed by much (I'm testing by clicking on regions since I cannot click on lines in windows). 

I've identified the two slow portions of the code. Building the list of visibles to highlight takes a lot of time when selecting neurons, but no time when deselecting. Adding properties to 'visible' objects is also slow, but for no obvious reason.

**Comment by csweaver** [comment]
Keep a list of visited objects so that we don't loop through nearly as many. Saves about 1-2s on my machine. Not a major speed up, but there is not much fat to trim from the code.
