### ISSUE TITLE
Unable to select regions

### ISSUE THREAD

**Issue by dteinferno** [JaneliaSciComp/Neuroptikon#74]
When I try to click on a region to select it in the new release, I get no response.

**Comment by csweaver** [comment]
Here is the error message Christopher got when he made the new release:

>When I tried testing the version of neuroptikon I had built, I found I was unable to select anything by clicking.
>I got some messages on the console like 
>  "Mouse click failed: object of type 'SwigPyObject' has no len() (TypeError)"
>which sounds sort of familiar.

I'll try to look into the error today.

**Comment by cmbruns-hhmi** [comment]
P {margin-top:0;margin-bottom:0;}



Hey Charlotte-

I actually made a second release last Friday that probably fixed this problem. The PolytopeIntersector class is now available on Windows, but does not work well enough. So I added a hook to continue not using PolytopeIntersector on Windows, even though the
 class now exists. 

-Christopher

**Comment by csweaver** [comment]
1.0.0r5 fixes the issue
