### ISSUE TITLE
Increase visibility to parent region when child region highlighted

### ISSUE THREAD

**Issue by csweaver** [JaneliaSciComp/Neuroptikon#75]
When a child region is highlighted (not necessarily selected) the parent region should be less opaque.

**Comment by csweaver** [comment]
@dteinferno I worded this issue too ambiguously. Could you explain exactly what you want? Is the title correct or the comment?

**Comment by dteinferno** [comment]
@csweaver I can't remember exactly what we wanted here. I'll think on it and talk to Vivek.

**Comment by dteinferno** [comment]
@csweaver Vivek couldn't remember either, so I'm going to close this issue for now, but will reopen it if I can recall exactly what we wanted.
