### ISSUE TITLE
Colors "hide" behind regions

### ISSUE THREAD

**Issue by dteinferno** [JaneliaSciComp/Neuroptikon#86]
![nkontwocolor](https://cloud.githubusercontent.com/assets/6876194/8864314/61e61f94-316e-11e5-94d8-45076b025e28.jpg)

When neurons are selected and assigned a color, the dark, dotted lines show up strongly throughout, but the colors are hidden behind the structures (see the included image).

**Comment by csweaver** [comment]
I'll try lowering the opacity of the highlight depending on region vs neuron/arborization.

**Comment by csweaver** [comment]
It was a different solution that I thought initially, but I've fixed it. Fixed in release 1.0.0rc13.
