### ISSUE TITLE
SelectObjectsRegex selects more than specified

### ISSUE THREAD

**Issue by dteinferno** [JaneliaSciComp/Neuroptikon#87]
If I use n1 = network.findObjectsRegex(Neuron,"Ebw*") or n2 = network.findObjectsRegex(Neuron,"Ebt*"), both commands select both sets of neurons with "Ebw" and "Ebt" in the name rather than the first one selecting only the Ebw neurons and the second selecting only the Ebt neurons.

**Comment by csweaver** [comment]
![screen shot 2015-07-29 at 9 31 27 am](https://cloud.githubusercontent.com/assets/1517263/8958761/a5be6428-35d4-11e5-8892-091bf472cc54.png)

It seems to work fine in my version. Do you have a different dataset than I do? I'm pulling the one off of the shared drive.

**Comment by dteinferno** [comment]
It also works fine for me now... I will close the issue and reopen it if I encounter the issue again and can figure out the circumstances. Thanks!
