### ISSUE TITLE
Display neuron's name when selected

### ISSUE THREAD

**Issue by dteinferno** [JaneliaSciComp/Neuroptikon#88]
When a process of a cell body is clicked, it would be nice if the neuron's name could be immediately displayed somewhere (say on the command line) rather than having to go through the inspector window.

**Comment by csweaver** [comment]
Just for neurons or for any type of object?

**Comment by dteinferno** [comment]
In our script, the regions already have labels displayed, so labeling the neurons alone is enough.

**Comment by csweaver** [comment]
You've got 2 new modes that you can select from the view menu: 
"Show neuron names on selection"  - shows the neuron names as overlays on the display
"Print neuron names on selection"  - prints the neuron names to the console.
