### ISSUE TITLE
Adding pre and post synaptic regions after creating a synapse

### ISSUE THREAD

**Issue by dteinferno** [JaneliaSciComp/Neuroptikon#92]
It would be nice to have a way to add pre and post synaptic regions to a given connection after making it. For example,
cxn = neuron1.synapseOn(neuron2)
cxn.preSynapticRegion = region

**Comment by csweaver** [comment]
It actually already works just as you have put in the example. 

```
cxn = neuron1.synapseOn(neuron2)
cxn.preSynapticRegion = region
```

I'll add that to the documentation
